# Generated by Django 4.1.2 on 2022-10-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_employee_created_on_alter_employee_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='job_level',
            field=models.CharField(choices=[('Jr.', 'Junior'), ('Reg', 'Regular'), ('Sr.', 'Senior')], max_length=20),
        ),
    ]
