# Generated by Django 4.1.2 on 2022-10-15 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_employee_job_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_level',
            field=models.CharField(choices=[('Jr.', 'Junior'), ('Reg', 'Regular'), ('Sr.', 'Senior')], max_length=20, verbose_name='Seniority level'),
        ),

    ]
