# Generated by Django 4.1.2 on 2022-10-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_accesscard_project_alter_employee_department_and_more'),
    ]


